title: K-9 Mail
description: "K-9 Mail is an open source email client focused on making it easy to chew through large volumes of email"
url: "https://k9mail.app"
github: k9mail
repository: k9mail/k9
timezone: Europe/Berlin

# Build settings
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-compose
  - jekyll-feed
  - jekyll-redirect-from

collections:
  documentation:
    output: "true"

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
